# Generated by Django 5.2.7 on 2026-01-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_delete_withdrawalrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wallet.paymenttransaction',),
        ),
    ]
