# Generated by Django 5.2.7 on 2026-01-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0023_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='withdrawal_details',
            field=models.TextField(blank=True, help_text='Bank / UPI / USDT details for withdrawal', null=True),
        ),
    ]
