# Generated by Django 5.2.7 on 2026-01-26 08:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0024_paymenttransaction_withdrawal_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='User uploaded payment proof', max_length=255, null=True, verbose_name='payment_screenshot'),
        ),
    ]
