# Generated by Django 5.2.7 on 2026-01-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_paymenttransaction_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='request_type',
            field=models.CharField(blank=True, choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], help_text='Deposit or Withdraw', max_length=10, null=True),
        ),
    ]
