# Generated by Django 5.2.7 on 2026-01-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0027_remove_paymentrequest_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='user_payment_method_details',
            field=models.TextField(blank=True, help_text='User provided UPI / Bank / USDT details for withdrawal', null=True),
        ),
    ]
