# Generated by Django 5.2.7 on 2026-01-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0028_paymentrequest_user_payment_method_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='user_payment_method',
            field=models.CharField(blank=True, help_text='UPI / Bank / USDT chosen by user', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='user_payment_method_details',
            field=models.TextField(blank=True, help_text='User entered payment details', null=True),
        ),
    ]
