# Generated by Django 5.2.7 on 2026-01-11 11:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tier', models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], max_length=20)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('min_daily_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('min_monthly_amount', models.DecimalField(decimal_places=2, default=Decimal('30000.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('interest_accrued', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_interest_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('frozen', 'Frozen')], default='active', max_length=20)),
                ('is_loan_eligible', models.BooleanField(default=False)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='committees.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'committee')},
            },
        ),
        migrations.CreateModel(
            name='CommitteeTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tx_type', models.CharField(choices=[('invest', 'Invest'), ('interest', 'Interest'), ('withdraw', 'Withdraw')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='committees.committeemembership')),
            ],
        ),
    ]
