# Generated by Django 5.2.7 on 2026-01-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0006_paymentplan_committeepaymentplan_usercommitteeplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeepaymentplan',
            name='interval',
            field=models.PositiveIntegerField(default=0, help_text='Days'),
        ),
        migrations.AddField(
            model_name='committeepaymentplan',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
