# Generated by Django 5.2.7 on 2026-01-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_committee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='investment_type',
        ),
        migrations.AddField(
            model_name='committee',
            name='daily_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='yearly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
