# Generated by Django 5.2.7 on 2026-01-13 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_usercommitteeplan_next_due_at_and_more'),
        ('notifications', '0005_alter_duenotification_user_committee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DueResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('pay_now', 'Pay Now'), ('pay_later', 'Pay Later')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.committee')),
                ('due_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='notifications.duenotification')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.paymentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
