# Generated by Django 5.2.7 on 2026-01-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_usercommitteeplan_next_due_at_and_more'),
        ('notifications', '0008_duenotification_target_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueresponse',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='committees.committee'),
        ),
        migrations.AlterField(
            model_name='dueresponse',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='committees.paymentplan'),
        ),
    ]
