# Generated by Django 5.2.7 on 2026-01-14 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_usercommitteeplan_next_due_at_and_more'),
        ('notifications', '0010_remove_duenotification_target_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dueresponse',
            constraint=models.UniqueConstraint(fields=('user', 'due_notification'), name='unique_user_due_response'),
        ),
    ]
