# Generated by Django 5.2.7 on 2026-01-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_remove_paymenttransaction_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='admin_note',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='user_committee',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='context',
            field=models.CharField(blank=True, choices=[('committee', 'Committee'), ('loan_emi', 'Loan EMI'), ('loan_due', 'Loan Due'), ('wallet', 'Wallet')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='reference_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='admin_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be paid', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference_id',
            field=models.CharField(blank=True, help_text='LoanDue ID / Committee ID / etc', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
