# Generated by Django 5.2.7 on 2026-01-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userverification_dl_number_userverification_dl_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverification',
            name='dl_number',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='dl_photo',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='govt_id_number',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='govt_id_photo',
        ),
    ]
