# Generated by Django 5.2.7 on 2026-01-25 16:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userverification_dl_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='usdt_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='aadhar_front_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aadhar_front'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='international_id_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='international_id'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='pan_card_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pan_card'),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='passport_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='passport'),
        ),
    ]
