# Generated by Django 5.2.7 on 2026-01-13 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_usercommitteeplan_next_due_at_and_more'),
        ('notifications', '0004_duenotification_user_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenotification',
            name='user_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='committees.usercommittee'),
        ),
    ]
