# Generated by Django 5.2.7 on 2026-01-14 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_usercommitteeplan_next_due_at_and_more'),
        ('notifications', '0006_dueresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteePaymentDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repeat_after_minutes', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.committee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.paymentplan')),
            ],
        ),
    ]
