# Generated by Django 5.2.7 on 2026-01-17 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_dueresponse_unique_user_due_response'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('loan', 'Loan'), ('committee', 'Committee'), ('wallet', 'Wallet'), ('custom', 'Custom')], max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='loan_id / loan_due_id / committee_id / etc', max_length=100, null=True)),
                ('heading', models.CharField(help_text='Short title e.g. EMI Due, Payment Reminder', max_length=120)),
                ('description', models.TextField(help_text='Detailed message shown to user')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('repeat_after_minutes', models.PositiveIntegerField(default=60)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universal_dues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UniversalDueResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('pay_now', 'Pay Now'), ('pay_later', 'Pay Later')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='notifications.universaldue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'due'), name='unique_universal_due_response')],
            },
        ),
    ]
