# Generated by Django 5.2.7 on 2026-01-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_paymenttransaction_user_committee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='admin_message',
            field=models.TextField(blank=True, help_text='Message shown to user after approval/rejection'),
        ),
    ]
