# Generated by Django 5.2.7 on 2026-01-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_paymenttransaction_admin_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
