# Generated by Django 5.2.7 on 2026-01-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0024_paymenttransaction_withdrawal_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='request_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='deposit', max_length=10),
        ),
    ]
