# Generated by Django 5.2.7 on 2026-01-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0025_paymentrequest_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='request_type',
        ),
    ]
