# Generated by Django 5.2.7 on 2026-01-10 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_grouppaymentinvite_invited_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouppaymentinvite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grouppaymentinvite',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='grouppaymentinvite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grouppaymentinvite',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grouppaymentinvite',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.purchaseplan'),
        ),
        migrations.RemoveField(
            model_name='grouppaymentinvite',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='grouppaymentinvite',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='grouppaymentinvite',
            name='is_payer',
        ),
        migrations.RemoveField(
            model_name='grouppaymentinvite',
            name='user',
        ),
    ]
