# Generated by Django 5.2.7 on 2026-01-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_rename_status_property_property_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='listing_status',
        ),
    ]
