# Generated by Django 5.2.7 on 2026-01-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_adminwallet_adminwalletentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Amount added to user's wallet", max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Amount deducted from user's wallet", max_digits=12),
        ),
    ]
