# Generated by Django 5.2.7 on 2026-01-18 06:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_wallettransaction_bonus_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='bonus_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
