# Generated by Django 5.2.7 on 2026-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loanplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanPlan',
        ),
        migrations.AddField(
            model_name='loan',
            name='investment_multiplier',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Eligible loan = investment × multiplier', max_digits=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_template',
            field=models.BooleanField(default=True, help_text='Admin-created loan template'),
        ),
        migrations.AddField(
            model_name='loan',
            name='min_committee_months',
            field=models.PositiveIntegerField(default=6, help_text='Minimum committee duration required'),
        ),
    ]
