# Generated by Django 5.2.7 on 2026-01-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(fields=('wallet', 'reference_id', 'tx_type', 'status'), name='unique_wallet_tx_once'),
        ),
    ]
