# Generated by Django 5.2.7 on 2026-01-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_paymenttransaction_is_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
