# Generated by Django 5.2.7 on 2026-01-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_paymenttransaction_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='context',
            field=models.CharField(choices=[('committee', 'Committee'), ('loan_emi', 'Loan EMI'), ('wallet', 'Wallet')], default='committee', max_length=20),
        ),
    ]
