# Generated by Django 5.2.7 on 2026-01-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_paymenttransaction_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='context',
        ),
    ]
