# Generated by Django 5.2.7 on 2026-01-17 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_remove_paymenttransaction_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='wallet_effect',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='wallet_synced',
            field=models.BooleanField(default=False),
        ),
    ]
