# Generated by Django 5.2.7 on 2026-01-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_paymentrequest_earned_paymentrequest_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Admin controlled bonus balance', max_digits=12),
        ),
    ]
