# Generated by Django 5.2.7 on 2026-01-18 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_remove_wallettransaction_bonus_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.paymentmethod'),
        ),
    ]
