# Generated by Django 5.2.7 on 2026-01-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_wallettransaction_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='payment_method',
        ),
    ]
