# Generated by Django 5.2.7 on 2026-01-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_remove_wallettransaction_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wallet.paymentrequest',),
        ),
    ]
