# Generated by Django 5.2.7 on 2026-01-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='withdrawal_details',
            field=models.TextField(blank=True, help_text='UPI / Bank / Wallet details entered by user', null=True),
        ),
    ]
