# Generated by Django 5.2.7 on 2026-01-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_paymenttransaction_withdrawal_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WithdrawalRequest',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='withdrawal_details',
        ),
    ]
