# Generated by Django 5.2.7 on 2026-01-26 09:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0026_paymentrequest_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='purpose',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='User uploaded payment proof', max_length=255, null=True, verbose_name='payment_screenshot'),
        ),
    ]
