# Generated by Django 5.2.7 on 2026-01-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_propertylistingrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='status',
            new_name='property_status',
        ),
        migrations.AddField(
            model_name='property',
            name='listing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
