# Generated by Django 5.2.7 on 2026-01-11 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeetransaction',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='min_daily_amount',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='min_monthly_amount',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='tier',
        ),
        migrations.AddField(
            model_name='committee',
            name='duration_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='committee',
            name='filled_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='committee',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='committee',
            name='investment_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='committee',
            name='roi_percent',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AddField(
            model_name='committee',
            name='total_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='committee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UserCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roi_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roi_unlock_date', models.DateTimeField(blank=True, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.committee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('user_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='committees.usercommittee')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_roi', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('user_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='committees.usercommittee')),
            ],
        ),
        migrations.DeleteModel(
            name='CommitteeMembership',
        ),
        migrations.DeleteModel(
            name='CommitteeTransaction',
        ),
    ]
