# Generated by Django 5.2.7 on 2026-01-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_remove_committeetransaction_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
