# Generated by Django 5.2.7 on 2026-01-13 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_remove_committee_investment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interval_days', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteePaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='committees.committee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committees.paymentplan')),
            ],
        ),
        migrations.CreateModel(
            name='UserCommitteePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_payment_due', models.DateTimeField()),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='committees.paymentplan')),
                ('user_committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_plan', to='committees.usercommittee')),
            ],
        ),
    ]
