# Generated by Django 5.2.7 on 2026-01-13 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0007_committeepaymentplan_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommitteeplan',
            name='next_due_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usercommitteeplan',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
