# Generated by Django 6.0 on 2026-01-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_investment_enabled_property_investors_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentpool',
            name='investors_required',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='property',
            name='investors_min',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='property',
            name='investors_required',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
