# Generated by Django 5.2.7 on 2026-01-20 12:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_ownernotification_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=120)),
                ('payment_mode', models.CharField(choices=[('single', 'Single Payment'), ('group', 'Group Payment')], max_length=10)),
                ('group_size', models.PositiveIntegerField(blank=True, help_text='Only required for group payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Request',
                'verbose_name_plural': 'Property Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
