# Generated by Django 5.2.7 on 2026-01-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_propertyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='group_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
