# Generated by Django 5.2.7 on 2026-01-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_propertylistingrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('sold', 'Sold'), ('rented', 'Rented'), ('pending', 'Pending'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20),
        ),
    ]
