# Generated by Django 5.2.7 on 2026-01-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_remove_committee_investment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee',
            name='investment_amount',
        ),
    ]
