# Generated by Django 6.0 on 2026-01-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_grouppaymentinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppaymentinvite',
            name='is_payer',
            field=models.BooleanField(default=False),
        ),
    ]
