# Generated by Django 5.2.7 on 2026-01-25 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_propertylistingrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertylistingrequest',
            options={},
        ),
        migrations.RenameField(
            model_name='propertylistingrequest',
            old_name='approved_at',
            new_name='paid_at',
        ),
        migrations.AlterField(
            model_name='propertylistingrequest',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='payment_pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertylistingrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
