# Generated by Django 5.2.7 on 2026-01-12 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_remove_committee_investment_amount'),
        ('wallet', '0003_paymentmethod_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='user_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='committees.usercommittee'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set by admin on approval', max_digits=12, null=True),
        ),
    ]
