# Generated by Django 5.2.7 on 2026-01-17 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_usercommitteeplan_next_due_at_and_more'),
        ('wallet', '0011_paymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='context',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='reference_note',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('investment', 'Investment'), ('withdrawal', 'Withdrawal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='user_committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='committees.usercommittee'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='admin_message',
            field=models.TextField(blank=True, help_text='Message shown to user after approval/rejection'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set by admin on approval', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference_id',
            field=models.CharField(blank=True, help_text='UPI ref / bank txn id / hash', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
