# Generated by Django 5.2.7 on 2026-01-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_userloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandue',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
