# Generated by Django 5.2.7 on 2026-01-14 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_usercommitteeplan_next_due_at_and_more'),
        ('notifications', '0007_committeepaymentdue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='duenotification',
            name='target_type',
            field=models.CharField(choices=[('user', 'Single User'), ('committee', 'Whole Committee')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='duenotification',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='committees.committee'),
        ),
        migrations.AlterField(
            model_name='duenotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
