# Generated by Django 5.2.7 on 2026-01-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_dueresponse_committee_alter_dueresponse_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duenotification',
            name='target_type',
        ),
    ]
