# Generated by Django 5.2.7 on 2026-01-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loandue_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('min_months_required', models.PositiveIntegerField(help_text='Minimum committee months required')),
                ('investment_multiplier', models.DecimalField(decimal_places=2, default=2.0, help_text='Eligible loan = investment × multiplier', max_digits=5)),
                ('default_duration_months', models.PositiveIntegerField(default=12)),
                ('interest_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emi_interval_months', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
