# Generated by Django 5.2.7 on 2026-01-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_delete_loanplan_loan_investment_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanEligibilityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_committee_months', models.PositiveIntegerField(default=6, help_text='Minimum months user must stay in committee')),
                ('investment_multiplier', models.DecimalField(decimal_places=2, default=2.0, help_text='Eligible loan = total investment × multiplier', max_digits=5)),
                ('default_duration_months', models.PositiveIntegerField(default=12, help_text='Used only for EMI preview')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='loan',
            name='investment_multiplier',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='is_template',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='min_committee_months',
        ),
    ]
