# Generated by Django 5.2.7 on 2026-01-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loaneligibilityconfig_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanEligibilityConfig',
        ),
    ]
