# Generated by Django 5.2.7 on 2026-01-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
