# Generated by Django 5.2.7 on 2026-01-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='dl_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='dl_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/dl/'),
        ),
        migrations.AddField(
            model_name='userverification',
            name='govt_id_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='govt_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/govt/'),
        ),
        migrations.AddField(
            model_name='userverification',
            name='international_id_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='international_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/international/'),
        ),
        migrations.AddField(
            model_name='userverification',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/passport/'),
        ),
    ]
