# Generated by Django 5.2.7 on 2026-01-28 03:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userverification_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='aadhar_back_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aadhar_back'),
        ),
    ]
